
package mws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MathServiceContract", targetNamespace = "http://mws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MathServiceContract {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "test", targetNamespace = "http://mws/", className = "mws.Test")
    @ResponseWrapper(localName = "testResponse", targetNamespace = "http://mws/", className = "mws.TestResponse")
    @Action(input = "http://mws/MathServiceContract/testRequest", output = "http://mws/MathServiceContract/testResponse")
    public double test(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendRequest", targetNamespace = "http://mws/", className = "mws.SendRequest")
    @ResponseWrapper(localName = "sendRequestResponse", targetNamespace = "http://mws/", className = "mws.SendRequestResponse")
    @Action(input = "http://mws/MathServiceContract/sendRequestRequest", output = "http://mws/MathServiceContract/sendRequestResponse")
    public String sendRequest(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
