
package mws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MathServiceContractImpService", targetNamespace = "http://mws/", wsdlLocation = "http://localhost:5555/mws/mathservice?wsdl")
public class MathServiceContractImpService
    extends Service
{

    private final static URL MATHSERVICECONTRACTIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException MATHSERVICECONTRACTIMPSERVICE_EXCEPTION;
    private final static QName MATHSERVICECONTRACTIMPSERVICE_QNAME = new QName("http://mws/", "MathServiceContractImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:5555/mws/mathservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MATHSERVICECONTRACTIMPSERVICE_WSDL_LOCATION = url;
        MATHSERVICECONTRACTIMPSERVICE_EXCEPTION = e;
    }

    public MathServiceContractImpService() {
        super(__getWsdlLocation(), MATHSERVICECONTRACTIMPSERVICE_QNAME);
    }

    public MathServiceContractImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MATHSERVICECONTRACTIMPSERVICE_QNAME, features);
    }

    public MathServiceContractImpService(URL wsdlLocation) {
        super(wsdlLocation, MATHSERVICECONTRACTIMPSERVICE_QNAME);
    }

    public MathServiceContractImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MATHSERVICECONTRACTIMPSERVICE_QNAME, features);
    }

    public MathServiceContractImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MathServiceContractImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MathServiceContract
     */
    @WebEndpoint(name = "MathServiceContractImpPort")
    public MathServiceContract getMathServiceContractImpPort() {
        return super.getPort(new QName("http://mws/", "MathServiceContractImpPort"), MathServiceContract.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MathServiceContract
     */
    @WebEndpoint(name = "MathServiceContractImpPort")
    public MathServiceContract getMathServiceContractImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mws/", "MathServiceContractImpPort"), MathServiceContract.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MATHSERVICECONTRACTIMPSERVICE_EXCEPTION!= null) {
            throw MATHSERVICECONTRACTIMPSERVICE_EXCEPTION;
        }
        return MATHSERVICECONTRACTIMPSERVICE_WSDL_LOCATION;
    }

}
